name: "Install Dependencies and Run Linter"
description: "Installs dependencies and runs the Rust linter."

inputs:
  working-directory:
    description: 'The working directory for the linter'
    required: true
    default: '.'

runs:
  using: "composite"
  steps:
    # Ensures to use the Rust toolchain version
    - uses: dsherret/rust-toolchain-file@v1
    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt install libdw-dev
        cargo install cargo-sort
        rustup update
        NIGHTLY=$(cat rust-nightly-toolchain)
        rustup toolchain install "$NIGHTLY"
        rustup component add clippy --toolchain "$NIGHTLY"
        rustup component add rustfmt --toolchain "$NIGHTLY"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run Linter
      run: |
        scripts/rust_lint.sh --check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
